# Generated by Django 3.0.7 on 2020-07-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'permissions': [('is_blogger', 'is Blogger')]},
        ),
    ]
